import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {PlayView,type HoleDoneInfo} from '../game/PlayView';
import {Avatar} from '../game/Avatar';
import {AvatarCustomizer} from '../game/AvatarCustomizer';
import {HEADS,HATS,FACES,SEATS,BALLS,headTones,type Avatar as AvatarSpec} from '../game/avatarParts';
import {EARNABLE_COLORS} from '../../server/potty/cosmeticCatalog';
import {DEFAULT_PARAMS} from '../sim/params';
import type {Hole} from '../sim/types';
import {isMuted,setMuted,unlockAudio} from '../game/sound';
import {prepareBathroomArt,ART} from './art';
import {BATH_THEMES,bathTheme,type BathThemeId} from './themes';
import {dailyKey,pickCourse} from './course';
import {PREVIEW_KEY,loadState,visit,stats,finishRound,total,relative,rel,type Round,type Result,type PreviewState} from './store';
import {CourseThumb,Dialog,Icon,PropIcon} from './components';
import poolData from './coursePool.json';
import './Bathroom.css';
const POOL=poolData as Hole[];
type Tab='home'|'match'|'map'|'ranks'|'profile';
type Modal='settings'|'help'|'look'|'challenges'|'name'|null;
const TOPICS=[{name:'Paper bumpers',prop:'paper',text:'Bouncy paper rolls add energy. Bank a shot off the gold contact ring.'},{name:'Plungers & partitions',prop:'plunger',text:'Solid obstacles. Use the porcelain walls for bank shots.'},{name:'Gum & bath mats',prop:'gum',text:'Gum grabs the ball. Rough mats slow it down. Plan your power.'},{name:'Puddles & drains',prop:'vent',text:'Hazards add a penalty and return the ball to safety. Look for a way around.'},{name:'Pipe shortcuts',prop:'pipe',text:'Aim into IN. The ball travels to OUT with its speed preserved. Some exits redirect it.'},{name:'Slopes & moving gates',prop:'soap',text:'Ramp arrows show the downhill pull. Watch a gate’s timing before you putt.'}]as const;
function uid(){return typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;}
async function preload(){await prepareBathroomArt();await Promise.all(['/art/avatar-locker-room.webp','/art/logo.webp',...['ace','albatross','eagle','birdie','par','over','double','triple','cap'].map(t=>`/art/results/${t}-mascot-v2.webp`)].map(src=>{const i=new Image();i.src=src;return i.decode();}));await document.fonts.ready;}
const minutes=(ms:number)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
function resultOf(r:Round):Result{return{id:r.id,title:r.title,mode:r.mode,date:r.date,finished:Date.now(),duration:Date.now()-r.started,holes:r.scores,bot:r.bot};}
export function BathroomApp(){
 const[state,setState]=useState<PreviewState>(()=>visit(loadState()));
 const[tab,setTab]=useState<Tab>('home'),[modal,setModal]=useState<Modal>(null),[ready,setReady]=useState(false),[bootError,setBootError]=useState(false),[savingError,setSavingError]=useState(false);
 const[run,setRun]=useState<Round|null>(null),runRef=useRef(run);runRef.current=run;
 const[runOffset,setRunOffset]=useState(0),[exitOpen,setExitOpen]=useState(false),[count,setCount]=useState(3),[theme,setTheme]=useState<BathThemeId|'all'>('all');
 const[generating,setGenerating]=useState<{done:number;total:number;failed?:boolean}|null>(null),worker=useRef<Worker|null>(null),generationTimer=useRef<ReturnType<typeof setTimeout>>();
 const[recap,setRecap]=useState<Result|null>(null),[rankMode,setRankMode]=useState<'thrones'|'daily'|'rounds'>('thrones'),[muted,setMutedUi]=useState(isMuted()),[draft,setDraft]=useState<AvatarSpec>(state.avatar),[draftName,setDraftName]=useState(state.name);
 const[today,setToday]=useState(dailyKey());
 const s=stats(state),daily=state.results.find(r=>r.mode==='daily'&&r.date===today);
 const reloadArt=()=>{setBootError(false);let timeout:ReturnType<typeof setTimeout>;Promise.race([preload(),new Promise<never>((_,reject)=>{timeout=setTimeout(()=>reject(Error('load')),20000);})]).then(()=>setReady(true)).catch(()=>setBootError(true)).finally(()=>clearTimeout(timeout));};
 useEffect(()=>{reloadArt();},[]);
 useEffect(()=>{try{localStorage.setItem(PREVIEW_KEY,JSON.stringify(state));setSavingError(false);}catch{setSavingError(true);}},[state]);
 useEffect(()=>{const update=()=>{const key=dailyKey();setToday(key);setState(p=>visit(p,key));};const interval=setInterval(update,60000);document.addEventListener('visibilitychange',update);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',update);};},[]);
 useEffect(()=>()=>{worker.current?.terminate();clearTimeout(generationTimer.current);},[]);
 useEffect(()=>{document.documentElement.classList.toggle('br-reduce',state.reduced);return()=>document.documentElement.classList.remove('br-reduce');},[state.reduced]);
 const changeTab=(next:Tab)=>{setTab(next);if(next==='ranks')setRankMode('thrones');document.querySelector('.br-scroll')?.scrollTo({top:0});};
 const begin=(holes:Hole[],mode:Round['mode'],title:string)=>{
  if(mode==='daily'&&daily){setRecap(daily);return;}
  unlockAudio();const now=Date.now();const next:Round={id:uid(),title,mode,date:today,started:now,holes,scores:[],...(mode==='practice'?{bot:holes.reduce((n,h)=>n+h.par,0)+2}: {})};
  setRunOffset(0);setRun(next);setState(p=>({...p,active:next}));setModal(null);setRecap(null);setExitOpen(false);
 };
 const tour=()=>begin([POOL[13],POOL[4],POOL[12],...POOL.filter((_,i)=>![13,4,12].includes(i))].slice(0,count),'tour','The Bathroom Tour');
 const startDaily=()=>{if(daily)setRecap(daily);else if(state.active?.mode==='daily'&&state.active.date===today)resume();else begin(pickCourse(POOL,'daily:'+today,3),'daily','The Daily Flush');};
 const resume=()=>{if(!state.active)return;setRunOffset(state.active.scores.length);setRun(state.active);};
 const stopWorker=()=>{worker.current?.terminate();worker.current=null;clearTimeout(generationTimer.current);};
 const random=()=>{stopWorker();setGenerating({done:0,total:count});const w=new Worker(new URL('./course.worker.ts',import.meta.url),{type:'module'});worker.current=w;const fail=()=>{stopWorker();setGenerating({done:0,total:count,failed:true});};w.onerror=fail;w.onmessage=e=>{if(w!==worker.current)return;const d=e.data;if(d.type==='progress')setGenerating({done:d.done,total:d.total});else if(d.type==='ready'){stopWorker();setGenerating(null);begin(d.holes,'random','Off the Roll');}else fail();};generationTimer.current=setTimeout(fail,45000);w.postMessage({seed:uid(),count,theme:theme==='all'?undefined:theme});};
 const done=(info:HoleDoneInfo)=>{const active=runRef.current;if(!active)return;const index=runOffset+info.holeIndex;if(active.scores[index])return;const next={...active,scores:[...active.scores,{id:info.hole.id,name:info.hole.name,theme:info.hole.theme??'bath-royal',par:info.hole.par,score:info.score,strokes:info.strokes.length,sunk:info.sunk}]};runRef.current=next;setRun(next);setState(p=>next.scores.length===next.holes.length?finishRound(p,next):{...p,active:next});};
 const finish=()=>{setRun(null);setExitOpen(false);changeTab('home');};
 const openLook=()=>{setDraft(state.avatar);setModal('look');};
 const toggleAudio=()=>{const next=!isMuted();setMuted(next);setMutedUi(next);if(!next)unlockAudio();};
 const unlocks={unlocked:Object.keys(HEADS),hats:Object.keys(HATS),faces:Object.keys(FACES),shirts:Object.keys(SEATS),balls:Object.keys(BALLS),colors:[...Object.keys(headTones(draft.head)),...Object.keys(EARNABLE_COLORS)],stats:{points:99999,rankedWins:99999,places:99999,dailyDays:99999,aces:99999,thrones:99999}};
 const scorecard=(r:Result,close:()=>void)=><div className="br-recap"><div className="br-recap-hero"><Icon name="trophy" size={48}/><span className="br-kicker">{r.bot!==undefined?(total(r)<r.bot?'PRACTICE VICTORY':total(r)===r.bot?'ALL SQUARE':'ROUND COMPLETE'):'ROUND COMPLETE'}</span><h2>{r.title}</h2><div className="br-score-orb">{rel(relative(r))}<small>TO PAR</small></div><div className="br-mini-stats"><span><b>{total(r)}</b> strokes</span><span><b>{r.holes.length}</b> holes</span><span><b>{minutes(r.duration)}</b> time</span></div>{r.bot!==undefined&&<p>You {total(r)} · Bogey Bob {r.bot} <small>Practice target</small></p>}</div><div className="br-score-table"><div className="br-table-head"><span>HOLE</span><span>PAR</span><span>YOU</span></div>{r.holes.map((h,i)=><div key={h.id+i}><span><i>{i+1}</i>{h.name}{h.sunk&&h.strokes===1&&<em>ACE</em>}</span><span>{h.par}</span><strong className={h.score<=h.par?'good':''}>{h.score}</strong></div>)}</div><p className="br-footnote">Saved to your preview records. {r.mode==='daily'?'A fresh Daily Flush arrives at midnight Eastern.':'Good putts. Better dumps.'}</p><button className="br-gold" onClick={close}>Back to the clubhouse <Icon name="arrow"/></button></div>;
 if(!ready)return <div className="br-app br-boot"><div className="br-boot-mark"><Icon name="crown" size={66}/></div><span className="br-kicker">THE BATHROOM TOUR</span><h1>{bootError?'Hold that flush.':'Polishing the porcelain.'}</h1><p>{bootError?'The artwork didn’t finish loading. Give it another go.':'Getting the whole game ready together.'}</p>{bootError?<button className="br-gold" onClick={reloadArt}>Try again</button>:<div className="br-loading-track"><i/></div>}<span className="br-preview-tag">DESIGN PREVIEW</span></div>;
 return <div className={`br-app ${run?'br-playing':''} ${state.reduced?'br-reduced':''}`}>
  {run?<PlayView key={run.id+':'+runOffset} holes={run.holes.slice(runOffset)} previewAvatar={state.avatar} previewReducedMotion={state.reduced} previewCrowd={state.crowd} previewPaused={exitOpen} holeNumberOffset={runOffset} previousRelative={run.scores.slice(0,runOffset).reduce((n,h)=>n+h.score-h.par,0)} lockedParams={DEFAULT_PARAMS} noRetry onExit={()=>setExitOpen(true)} exitLabel="Pause round" onHoleDone={done} renderDoneCard={(_,actions)=><button className="br-gold" onClick={actions.next}>{run.scores.length===run.holes.length?'View round recap':'Next hole'}<Icon name="arrow"/></button>} renderScorecard={()=> <div className="br-overlay"><section className="br-dialog br-score-dialog" role="dialog" aria-modal="true" aria-label="Round recap">{scorecard(state.results.find(r=>r.id===run.id)??resultOf(run),finish)}</section></div>}/>:<>
  <header className="br-topbar"><button className="br-wordmark" onClick={()=>changeTab('home')} aria-label="Home">PUTT PUTT <b>POTTY<span>™</span></b></button><span className="br-preview-tag">PREVIEW</span><div className="br-top-actions"><button className="br-circle" onClick={()=>setModal('settings')} aria-label="Settings"><Icon name="gear"/></button><button className="br-player-pill" onClick={()=>changeTab('profile')} aria-label="Your profile"><Avatar av={state.avatar} size={34}/><span><b>{s.crowns.length}</b><Icon name="crown" size={15}/></span></button></div></header>
  <main className="br-scroll" key={tab}>
  {savingError&&<p className="br-notice" role="status">Your browser couldn’t save preview progress. Keep this tab open to keep playing.</p>}
  {tab==='home'&&<>
   <section className="br-hero"><img src={ART+'hero.webp'} alt="The crowned Putt Putt Potty mascot in a bathroom mini-golf arena"/><div className="br-hero-copy"><span className="br-kicker">THE BATHROOM TOUR</span><h1>BIG PUTTS.<br/><em>ROYAL FLUSHES.</em></h1><p>Same filthy good game.<br/>A whole new bathroom.</p></div><div className="br-hero-bottom"><span><Icon name="flag" size={16}/> 14 holes · 6 bathrooms · endless remixes</span><button className="br-gold" onClick={tour}>Play the bathroom tour <Icon name="arrow"/></button></div></section>
   {state.active&&<button className="br-resume" onClick={resume}><Icon name="flag"/><span><b>Finish what you started</b><small>{state.active.title} · {state.active.scores.length}/{state.active.holes.length} holes complete</small></span><Icon name="arrow"/></button>}
   <div className="br-feature-grid"><button className={`br-feature br-daily ${daily?'complete':''}`} onClick={startDaily}><div><Icon name="flag" size={28}/><span className="br-kicker">DAILY FLUSH</span><Icon name="arrow" size={20}/></div><h2>{daily?'Your round is in.':'One round. Every day.'}</h2><p>{daily?'Tap for your full scorecard.':'Three holes. Make them count.'}</p><div className="br-feature-score">{daily?<><strong>{rel(relative(daily))}</strong><span>TO PAR<small>{total(daily)} strokes · view recap</small></span></>:<><strong>3</strong><span>FRESH HOLES<small>Play today’s course</small></span></>}</div></button>
   <button className="br-feature br-quick" onClick={()=>begin(pickCourse(POOL,uid(),3),'practice','Quick Match')}><div><Icon name="match" size={28}/><span className="br-kicker">QUICK MATCH</span><Icon name="arrow" size={20}/></div><h2>Beat Bogey Bob.</h2><p>Three-hole practice matchup.</p><div className="br-record"><span><strong>{s.wins}</strong> WINS</span><span><strong>{s.losses}</strong> LOSSES</span></div></button></div>
   <div className="br-section-heading"><div><span className="br-kicker">FIND YOUR NEXT THRONE</span><h2>Six rooms. Zero manners.</h2></div><button className="br-text" onClick={()=>changeTab('map')}>Explore <Icon name="arrow" size={17}/></button></div>
   <div className="br-venue-strip">{BATH_THEMES.map(t=><button key={t.id} className="br-small-venue" style={{'--venue':t.color}as CSSProperties} onClick={()=>{setTheme(t.id);changeTab('match');}}><CourseThumb hole={POOL.find(h=>h.theme===`bath-${t.id}`)!}/><span>{t.tag}</span><h3>{t.name}</h3></button>)}</div>
   <button className="br-help-link" onClick={()=>setModal('help')}><Icon name="flag"/><span>New obstacles. Same short game.<small>Get to know the bathroom.</small></span><Icon name="arrow"/></button>
  </>}
  {tab==='match'&&<>
   <div className="br-page-heading"><span className="br-kicker">PICK YOUR PUTTS</span><h1>LET IT <em>ROLL.</em></h1><p>Bank it. Bounce it. Flush it.</p></div>
   <section className="br-match-card"><div className="br-versus"><div><Avatar av={state.avatar} size={110}/><b>{state.name}</b><small>YOUR SHORT GAME</small></div><strong>VS</strong><div><Avatar av={{head:'classic',porcelain:'gold',seat:'red',hat:'cap',face:'happy',ball:'white'}} size={110}/><b>Bogey Bob</b><small>PRACTICE TARGET</small></div></div><div className="br-record-line"><span><b>{s.wins}</b> WINS</span><span><b>{s.losses}</b> LOSSES</span><span><b>{s.draws}</b> DRAWS</span></div><button className="br-gold" onClick={()=>begin(pickCourse(POOL,uid(),3,theme==='all'?undefined:theme),'practice','Quick Match')}>Play quick match <Icon name="match"/></button><p className="br-footnote">A local practice matchup. Fewest strokes wins.</p></section>
   <button className="br-daily-wide" onClick={startDaily}><div className="br-daily-icon"><Icon name="flag" size={38}/></div><span><span className="br-kicker">THE DAILY FLUSH</span><h2>{daily?'Nicely flushed.':'Your daily dose of putt.'}</h2><small>{daily?'Round complete · view your scorecard':'A new three-hole challenge every day'}</small></span><strong>{daily?rel(relative(daily)):'3'}<small>{daily?'TO PAR':'HOLES'}</small></strong></button>
   <section className="br-panel"><div className="br-section-heading"><div><span className="br-kicker">BUILD YOUR ROUND</span><h2>Your bathroom. Your rules.</h2></div><Icon name="random" size={28}/></div><label className="br-label">ROUND LENGTH</label><div className="br-segments">{[3,6,9,14].map(n=><button className={count===n?'selected':''} key={n} onClick={()=>setCount(n)}>{n}<small>holes</small></button>)}</div><label className="br-label" htmlFor="bathroom-theme">BATHROOM</label><select id="bathroom-theme" value={theme} onChange={e=>setTheme(e.target.value as BathThemeId|'all')}><option value="all">The whole bathroom tour</option>{BATH_THEMES.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="br-two-buttons"><button className="br-gold" onClick={()=>theme==='all'?tour():begin(POOL.filter(h=>h.theme===`bath-${theme}`),'venue',bathTheme(theme).name)}>Play {theme==='all'?'the tour':'this venue'}<Icon name="flag" size={20}/></button><button className="br-blue" onClick={random}>Roll a new course <Icon name="random" size={20}/></button></div><p className="br-footnote">Venue tours feature their designed holes. “Roll a new course” creates {count} new layouts with your chosen theme.</p></section>
  </>}
  {tab==='map'&&<>
   <div className="br-page-heading"><span className="br-kicker">THE THRONE DIRECTORY</span><h1>FIND YOUR <em>FLUSH.</em></h1><p>Six bathrooms. Six very different ways to go.</p></div><div className="br-passport"><Icon name="crown" size={40}/><div><b>{s.crowns.length} / 6</b><span>PREVIEW THRONES CLAIMED</span><small>Make par or better on a hole to claim its room.</small></div></div>
   <div className="br-venue-grid">{BATH_THEMES.map((t,i)=><section className="br-venue-card" key={t.id} style={{'--venue':t.color}as CSSProperties}><div className="br-venue-art"><CourseThumb hole={POOL.find(h=>h.theme===`bath-${t.id}`)!}/><span className="br-venue-number">0{i+1}</span>{s.crowns.includes(`bath-${t.id}`)&&<span className="br-claimed"><Icon name="crown" size={16}/> CLAIMED</span>}</div><div className="br-venue-copy"><span className="br-kicker">{t.tag}</span><h2>{t.name}</h2><p>{t.desc}</p><button className="br-blue" onClick={()=>begin(POOL.filter(h=>h.theme===`bath-${t.id}`),'venue',t.name)}>Play {POOL.filter(h=>h.theme===`bath-${t.id}`).length} holes <Icon name="arrow" size={18}/></button></div></section>)}</div>
  </>}
  {tab==='ranks'&&<>
   <div className="br-page-heading"><span className="br-kicker">YOUR PREVIEW RECORDS</span><h1>CHASE THE <em>CROWN.</em></h1><p>Every good round deserves a little bragging.</p></div><div className="br-segments br-rank-tabs">{[['thrones','Total thrones'],['daily','Daily course'],['rounds','Round history']].map(([v,label])=><button key={v} className={rankMode===v?'selected':''} onClick={()=>setRankMode(v as typeof rankMode)}>{label}</button>)}</div>
   {rankMode==='thrones'?<><div className="br-rank-player"><span className="br-position">1</span><Avatar av={state.avatar} size={70}/><div><h2>{state.name}</h2><small>YOUR BATHROOM TOUR</small></div><strong>{s.crowns.length}<small>THRONES</small></strong></div><div className="br-panel"><h2>Your throne cabinet</h2><div className="br-cabinet">{BATH_THEMES.map(t=><div className={s.crowns.includes(`bath-${t.id}`)?'claimed':''} key={t.id}><Icon name="crown" size={38}/><b>{t.name}</b><small>{s.crowns.includes(`bath-${t.id}`)?'Claimed':'Make par or better'}</small></div>)}</div></div></>:rankMode==='daily'?<section className="br-panel"><span className="br-kicker">{today} · 3 HOLES</span><h2>The Daily Flush</h2>{daily?<button className="br-daily-record" onClick={()=>setRecap(daily)}><Avatar av={state.avatar} size={70}/><span><b>{state.name}</b><small>{minutes(daily.duration)} · View recap</small></span><strong>{rel(relative(daily))}<small>{total(daily)} STROKES</small></strong></button>:<div className="br-empty"><Icon name="flag" size={52}/><h3>The porcelain is calling.</h3><p>Your daily result will appear here after the round.</p><button className="br-gold" onClick={startDaily}>Play the daily flush <Icon name="arrow"/></button></div>}</section>:<section className="br-panel"><h2>Every round. Every flush.</h2>{state.results.length?state.results.map(r=><button className="br-history" key={r.id} onClick={()=>setRecap(r)}><Icon name={r.mode==='daily'?'flag':'trophy'}/><span><b>{r.title}</b><small>{r.date} · {r.holes.length} holes</small></span><strong>{rel(relative(r))}</strong><Icon name="arrow" size={18}/></button>):<div className="br-empty"><Icon name="trophy" size={48}/><p>Finish a round to start your collection.</p><button className="br-gold" onClick={tour}>Play the tour</button></div>}</section>}
   <p className="br-footnote">These are your local preview records. Your live leaderboard and account are protected.</p>
  </>}
  {tab==='profile'&&<>
   <section className="br-profile"><div className="br-profile-backdrop"/><span className="br-kicker">YOUR PROFILE · YOUR KINGDOM</span><div className="br-profile-content"><div className="br-profile-golfer"><Avatar av={state.avatar} size={200}/><span>GOOD PUTTS.<br/>BETTER DUMPS.</span></div><div className="br-profile-info"><button className="br-name" onClick={()=>{setDraftName(state.name);setModal('name');}}><h1 style={{fontSize:`clamp(22px,${Math.min(8,105/state.name.length)}vw,50px)`}}>{state.name}</h1><span>EDIT</span></button><span className="br-title-pill"><Icon name="crown" size={14}/> {s.level>4?'PORCELAIN PRINCE':'THRONE CHASER'}</span><div className="br-level"><b>LVL {s.level}</b><span>{s.xp%200} / 200 TP</span><div><i style={{width:`${s.xp%200/2}%`}}/></div><small>{200-s.xp%200} TP to the next level</small></div><button className="br-gold" onClick={openLook}>Customize my look <Icon name="arrow" size={18}/></button></div></div></section>
   <div className="br-stat-grid">{[[s.crowns.length,'THRONES','crown'],[s.aces,'ACES','flag'],[s.rounds,'ROUNDS','match'],[s.streak,'DAY STREAK','clock']].map(([n,label,icon])=><div key={label}><Icon name={String(icon)} size={27}/><strong>{n}</strong><small>{label}</small></div>)}</div>
   <button className="br-help-link" onClick={()=>setModal('challenges')}><Icon name="trophy" size={36}/><span>Challenges<small>A little extra reason to sink the next one.</small></span><Icon name="arrow"/></button>
   <section className="br-panel"><div className="br-section-heading"><h2>Recent flushes</h2><button className="br-text" onClick={()=>{changeTab('ranks');setRankMode('rounds');}}>View all</button></div>{state.results.length?state.results.slice(0,3).map(r=><button className="br-history" key={r.id} onClick={()=>setRecap(r)}><Icon name="flag"/><span><b>{r.title}</b><small>{r.date}</small></span><strong>{rel(relative(r))}</strong></button>):<p className="br-footnote">Your next good putt belongs here.</p>}</section>
   <p className="br-footnote">All wardrobe items are available to try in this preview.</p>
  </>}
  <footer className="br-page-footer"><Icon name="crown" size={19}/> GOOD PUTTS. BETTER DUMPS.</footer>
  </main>
  <nav className="br-nav" aria-label="Main navigation">{([['home','Home','home'],['match','Match','match'],['map','Thrones','map'],['ranks','Ranks','trophy'],['profile','Profile','profile']]as const).map(([id,label,icon])=><button key={id} onClick={()=>changeTab(id)} className={tab===id?'selected':''} aria-current={tab===id?'page':undefined}><Icon name={icon} size={28}/><span>{label}</span></button>)}</nav>
  </>}
  {modal==='look'&&<AvatarCustomizer avatar={draft} onChange={setDraft} busy={false} error={null} onClose={()=>setModal(null)} onSave={()=>{setState(p=>({...p,avatar:draft}));setModal(null);}} headProgress={unlocks} progressLoading={false}/>}
  {modal==='settings'&&<Dialog title="Your controls" onClose={()=>setModal(null)}><button className="br-setting" onClick={toggleAudio}><span><b>Game sound</b><small>Hits, flushes and celebrations</small></span><span className={`br-switch ${!muted?'on':''}`} role="switch" aria-checked={!muted} aria-label="Game sound"/></button><button className="br-setting" onClick={()=>setState(p=>({...p,reduced:!p.reduced}))}><span><b>Reduce motion</b><small>Quieter cards and spectator animation</small></span><span className={`br-switch ${state.reduced?'on':''}`} role="switch" aria-checked={state.reduced} aria-label="Reduce motion"/></button><button className="br-setting" onClick={()=>setState(p=>({...p,crowd:!p.crowd}))}><span><b>The gallery</b><small>Keep the crowd around your course</small></span><span className={`br-switch ${state.crowd?'on':''}`} role="switch" aria-checked={state.crowd} aria-label="Crowd"/></button><button className="br-blue" onClick={()=>setModal('help')}>How to putt <Icon name="arrow"/></button><p className="br-footnote">A separate design preview. Play, experiment and customize freely. Your current game is protected.</p></Dialog>}
  {modal==='help'&&<Dialog title="Know your bathroom" onClose={()=>setModal(null)}><div className="br-help-intro"><b>Pull back. Let it roll.</b><p>Drag anywhere to aim and set power, then release to putt. Pull farther for a stronger shot. Bring the drag back near its start to cancel. Hold while the ball rolls to fast-forward.</p></div><div className="br-obstacle-guide">{TOPICS.map(item=><div key={item.name}><PropIcon name={item.prop} size={68}/><span><b>{item.name}</b><p>{item.text}</p></span></div>)}</div></Dialog>}
  {modal==='name'&&<Dialog title="Make a name for yourself" onClose={()=>setModal(null)}><label className="br-label" htmlFor="preview-name">PLAYER NAME</label><input id="preview-name" value={draftName} maxLength={18} onChange={e=>setDraftName(e.target.value)} autoComplete="off"/><p className="br-footnote">18 characters max. One line. All you.</p><button className="br-gold" disabled={!draftName.trim()} onClick={()=>{setState(p=>({...p,name:draftName.trim()}));setModal(null);}}>Save name</button></Dialog>}
  {modal==='challenges'&&<Dialog title="Chase a little glory" onClose={()=>setModal(null)}><div className="br-challenge-summary"><Icon name="trophy" size={38}/><span><b>{s.xp} TP</b><small>EARNED IN THE PREVIEW</small></span><span><b>{s.streak}</b><small>DAY STREAK</small></span></div>{[{name:'Take the tour',text:'Finish a round',current:s.rounds,target:1},{name:'Straight to royalty',text:'Sink a hole in one',current:s.aces,target:1},{name:'A full house',text:'Claim all six bathroom themes',current:s.crowns.length,target:6},{name:'Just one more flush',text:'Complete 18 holes',current:s.holes,target:18}].map(ch=><div className={`br-challenge ${ch.current>=ch.target?'complete':''}`} key={ch.name}><div><b>{ch.name}</b><span>{ch.current>=ch.target?<Icon name="check" size={20}/>:<>{ch.current}/{ch.target}</>}</span></div><p>{ch.text}</p><div className="br-progress"><i style={{width:`${Math.min(100,ch.current/ch.target*100)}%`}}/></div></div>)}<p className="br-footnote">15 TP per hole · 35 bonus TP per ace · 50 TP per new throne · 40 TP per practice win.</p></Dialog>}
  {recap&&<Dialog title="Your round recap" onClose={()=>setRecap(null)}>{scorecard(recap,()=>setRecap(null))}</Dialog>}
  {exitOpen&&<Dialog title="Taking a bathroom break?" onClose={()=>setExitOpen(false)}><p>Your completed holes are saved. You can resume from the start of the unfinished hole.</p><button className="br-gold" onClick={()=>setExitOpen(false)}>Keep putting <Icon name="arrow"/></button><button className="br-blue" onClick={finish}>Save & return to clubhouse</button></Dialog>}
  {generating&&<Dialog title={generating.failed?'Let’s roll that again.':'Unrolling your course'} onClose={()=>{stopWorker();setGenerating(null);}}><div className="br-generation"><PropIcon name="paper" size={130}/><h3>{generating.failed?'That layout needs a rethink.':`${generating.done} of ${generating.total} holes ready`}</h3><p>{generating.failed?'Try another roll, or jump straight into the tested Bathroom Tour.':'Building shapes, placing obstacles and checking the route.'}</p><div className="br-progress"><i style={{width:`${generating.done/generating.total*100}%`}}/></div></div>{generating.failed&&<><button className="br-gold" onClick={random}>Try a fresh roll <Icon name="random"/></button><button className="br-blue" onClick={()=>{setGenerating(null);tour();}}>Play the bathroom tour</button></>}</Dialog>}
 </div>;
}
